app = "human-checkpoint-getlarge"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile.fly"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
